version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=product-service
    networks:
      - microservice-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=order-service
      - PRODUCT_SERVICE_URL=http://product-service:8081
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
